fruits = []

f1 = input("Enter friuts name:")
fruits.append(1)
f2 = input("Enter friuts name:")
fruits.append(2)
f3 = input("Enter friuts name:")
fruits.append(3)
f4 = input("Enter friuts name:")
fruits.append(4)
f5 = input("Enter friuts name:")
f7 = input("Enter friuts name:")
fruits.append(7)
fruits.append(5)
f6 = input("Enter friuts name:")
fruits.append(6)
print(fruits)